### ISSUE TITLE
Future Enhancements Ideas

### ISSUE THREAD

**Issue by cgaspard** [cgaspard/mantiskanban#26]
If you have an idea, and want to share it, please post here, and I'll keep a running list of items I will be working on.

New features that will be implemented:  
1.   Link to mantis projects from the Kanban
2.   Due date field
3.   Enforce required fields
4.   Support for all custom fields (See issue #31)
5.   User color customization (See issue #34)
6.   Check for null in task list (See issue #30)

Done in "dev" branch (see demo server)
1.   Gravatar integration
2.   Display issue history in history tab
3.   History Tab (requires mantis 1.3)
4.   Task or SubTasks (requires mantis 1.3)
5.   Theme support
6.   Added Severity & Resolution fields

Ideas for future:
1.   Allow for a list of issues to be hidden
2.   Additional fields / Custom Fields Display
3.   Monitoring for issues and / or projects
4.   Swim Lanes (By user and / or custom field)

Completed Items:
1.   Link to mantis for issues and projects
2.   Allow links to automatically open items (http://mantis.com/mantiskanban/index.html?issue=1234)
3.   Sub-Project Support - completed but in testing

**Comment by ronlinet** [comment]
Reuse mantis authentication. 
To to access a kanban board user have to go through the authentication process what ever he is logged in the tracking system or not. Wouldn't it be more convenient to reuse the mantis authentication mechanism and let the user in if he is already authenticated ?
