### ISSUE TITLE
In new fresh MantisBT 1.2.17 install after upload/unzip mantiskanban-dev in plugins, is not recognized. Problems to login depending of the browser and url in it

### ISSUE THREAD

**Issue by edupulpillo** [cgaspard/mantiskanban#33]
Hi,
Just made a fresh install MantisBT 1.2.17 in LAMP and upload mantiskanban-dev in plugins folder.
Inside Mantis the mantiskanban do not appear as available. I changed the plugin folder name to mantiskanban , MantisKanban, but the plugin do not appears inside mantis in manage plugins as available.
Another plugins are inmediatly recognized after uploading and unzipping it.
¿What is needed to do that Mantis display the mantiskanban plugin as available?
Steps to reproduce: 
1)In a fresh MantisBT 1.2.17 installation upload the branch mantiskanban-dev.zip file inside /plugins
2)decompress the file
3)rename the folder mantiskanban-dev to mantiskanban and MantisKanban and observe that the plugin is not displayed in manage plugin section, but another plugins can be recognized.
Thanks!

**Comment by hydezhao** [comment]
hello @edupulpillo, I am facing the same error when trying to log on:
Error: Cannot read property 'documentElement' of null

How did you fix it ?

**Comment by gigaga** [comment]
+1
