### ISSUE TITLE
Sub-projects

### ISSUE THREAD

**Issue by sadortun** [cgaspard/mantiskanban#43]
Hello!

First of all, excellent job on the plugin !  It's giving a new life to Mantis !

It seems that the ScrumBucket doesnt work when assosiated to a sub-project.

Thanks,
Samuel

**Comment by cgaspard** [comment]
Hi Samuel

Make sure that you have the scrum bucket custom field associates with the parent and subproject individually.

Let me know if that doesn't help.

Corey

**Comment by sadortun** [comment]
Great ! Thanks!

**Comment by cgaspard** [comment]
Hi @sadortun , just wanted to verify your issue went away so I can close this out.

Thanks

**Comment by sadortun** [comment]
Yes,, i was unable to reproduce it. You can close the issue. Thanks
